# This is a basic workflow to help you get started with Actions

name: BlogServerCI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/blog-server:latest

      - name: Deploy 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            OLD_DOCKER_CONTAINER_ID=`docker ps -a |grep liaoliaojun/blog-server:latest | awk '{ print $1 }'`
            OLD_DOCKER_IMAGE_ID=`docker images liaoliaojun/blog-server:latest -q`

            if [ $OLD_DOCKER_CONTAINER_ID ]; then
              docker stop $OLD_DOCKER_CONTAINER_ID
              docker rm -f $OLD_DOCKER_CONTAINER_ID
            fi

            if [ $OLD_DOCKER_IMAGE_ID ]; then
              docker rmi -f $OLD_DOCKER_IMAGE_ID
            fi

            docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}
            docker pull liaoliaojun/blog-server:latest
            docker run -d -p 3000:3000 -v /www/blog/live:/app/live/ liaoliaojun/blog-server:latest
            
